disabled = false
locale = "en"
label = "English"
weight = 1
title = "MIT Spatial Sound Lab"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "A community studio for researching the social possibilities of immersive audio for public performance."
  copyright = "MIT Spatial Sound Lab"
